### ISSUE TITLE
Links need to be fixed in the Team section

### ISSUE THREAD

**Issue by riomyers** [chrissmejia/GuldIO#2]
There are a few broken links in the Team section, specifically Cindy's, Fernando's, Juan's and Aldo's that lead to https://a.com instead of their actual domains/URLs

I can fix them if someone provides me with their domain names, obviously I know Cindy's so I do not need that one.

**Comment by chrissmejia** [comment]
Thanks

**Comment by riomyers** [comment]
no worries dude!
